config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :apartments do
    :filters
  end

  get "/onboarding", to: "onboarding#new"
  post "/onboarding", to: "onboarding#create"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :statuses, only:[:new, :create]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_image_carousel.html.erb
<% if @apartment.photos.attached?  %>
  <div id="carouselExampleControls" class="carousel slide w-75 m-auto" data-bs-ride="carousel">
    <div class="carousel-inner h-100 position-relative">
      <%= link_to "X", apartments_path, style: "color: white; position: absolute; top: 4px; right: 4px; z-index: 100; text-decoration: none; margin-right: 25px; font-size: 60px;", data: {turbolinks: false}%>

      <%# The code below is not working for me... (font awesome icon) %>

      <%# <%= link_to apartments_path, {class: "exitcarousel"} do %>
        <%# <i class="fa-thin fa-circle-x" style="colod: red;"></i> %>
      <%# <% end %>

      <div class="carousel-item active h-100">
        <img class="main-img d-block w-100 h-100" src="<%= cl_image_path @apartment.photos.first.key %>" alt="" style="object-fit: cover;">
      </div>
      <% @apartment.photos[1..].each do |photo| %>
        <div class="carousel-item h-80">
          <img class="d-block w-100 h-80"  src="<%= cl_image_path photo.key %>" alt="" style="">
        </div>

      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to apartments_path, class: "navbar-brand" do %>
    <h1 class="navbar-header"><%= image_tag "favicon3.png", style:"height: 40px; margin-right:5px; margin-top:3px;" %>TauschMe</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "About", root_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Press", "", class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
        <%else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_chatroom.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div style="width: 12%;"></div>
    <%= link_to apartments_path, class: "navbar-brand" do %>
    <h1 class="navbar-header"><%= image_tag "favicon3.png", style:"height: 40px; margin-right:5px; margin-top:3px;" %>TauschMe</h1>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Back", :back, class: "nav-link"%>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        <%else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_index.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div style="width: 12%;"></div>
        <%= link_to root_path, class: "navbar-brand" do %>
        <h1 class="navbar-header"><%= image_tag "favicon3.png", style:"height: 40px; margin-right:5px; margin-top:3px;" %>TauschMe</h1>
        <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Matches", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path , class: "nav-link" %>
         <li class="nav-item active">
            <%= link_to "Back", :back, class: "nav-link", data: {turbolinks: false}%>
          </li>
        </ul>
      </div>
  </div>
</div>

app/views/shared/_navbar_loggedin.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to apartments_path, class: "navbar-brand" do %>
    <h1 class="navbar-header"><%= image_tag "favicon3.png", style:"height: 40px; margin-right:5px; margin-top:3px;" %>TauschMe</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item active">
            <%= link_to "About", root_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Matches", chatrooms_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>
        <%else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_onboarding.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div style="width: 12%;"></div>
    <%= link_to root_path, class: "navbar-brand" do %>
    <h1 class="navbar-header"><%= image_tag "favicon3.png", style:"height: 40px; margin-right:5px; margin-top:3px;" %>TauschMe</h1>

    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Back", :back, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
         <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, class: "nav-link", method: :delete %>

        <%else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_show.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div style="width: 12%;"></div>
        <%= link_to apartments_path, class: "navbar-brand" do %>
        <h1 class="navbar-header"><%= image_tag "favicon3.png" %>TauschMe</h1>
        <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Matches", chatrooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Home", root_path , class: "nav-link" %>
         <li class="nav-item active">
            <%= link_to "Back", :back, class: "nav-link", data: {turbolinks: false}%>
          </li>
        </ul>
      </div>
  </div>
</div>