config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :apartments do
    :filters
  end

  get "/onboarding", to: "onboarding#new"
  post "/onboarding", to: "onboarding#create"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :statuses, only:[:new, :create]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController

  def new
    @apartment = Apartment.new
    @filter = Filter.new
  end

  def create
    @apartment = Apartment.new(apartment_params)
    @apartment.user = current_user

    @filter = Filter.new(filter_params)
    @filter.user = current_user


    if @apartment.save && @filter.save
      redirect_to apartments_path
    else
      render 'new'
    end
  end

  private

  def apartment_params
    params.require(:apartment).permit(:title, :description, :room, :area, :rent, photos: [])
  end

  def filter_params
    params.require(:filter).permit(:room, :area, :rent)
  end
end

app/views/onboarding/_apartment_form.html.erb
<div class='apartment-form'>
  <h3 class="fw-normal mb-5 text-center" style="color: #A1BE97;">The Apartment I Want To Exchange</h3>

  <div class="form-outline form-white">
    <label class="form-label" style="color: #000000;" for="form3Examplea2">Title</label>
    <%= onboarding_form.text_field "apartment[title]", class: "form-control form-control-lg" %>
  </div>

  <div class="form-outline form-white">
    <label class="form-label not-top-label" style="color: #000000;" for="form3Examplea2">Kiez</label>
    <%= onboarding_form.text_field "apartment[area]", class: "form-control form-control-lg" %>
  </div>


  <div class="form-outline form-white">
    <label class="form-label not-top-label" style="color: #000000;" for="form3Examplea3">Rooms</label>
    <%= onboarding_form.text_field "apartment[room]", class: "form-control form-control-lg" %>
  </div>

  <div class="form-outline form-white">
    <label class="form-label not-top-label" style="color: #000000;" for="form3Examplea4">Rent</label>
    <%= onboarding_form.text_field "apartment[rent]", class: "form-control form-control-lg" %>
  </div>

    <div class="form-outline form-white">
    <label class="form-label not-top-label" for="form3Examplea4">Photo(s)</label>
    <%= onboarding_form.file_field "apartment[photos]", multiple: true, class: "form-control form-control-lg"  %>
  </div>

  <div class="form-outline form-white">
    <label class="form-label not-top-label" style="color: #000000;" for="form3Examplea5">Description</label>
    <%= onboarding_form.text_area "apartment[description]", class: "form-control form-control-lg" %>
  </div>

</div>

app/views/onboarding/_filter_form.html.erb
<div class='right-side-forms'>
  <div class='filter-form'>
    <h3 class="fw-normal mb-5 text-center" style="color: #A1BE97;">The Apartment I&#8217;m Looking For</h3>

    <div class="form-outline form-white">
      <label class="form-label" for="form3Examplea2" style="color: black;">Kiez</label>
      <%= onboarding_form.text_field "filter[area]", class: "form-control form-control-lg" %>
    </div>

    <div class="form-outline form-white not-top-label">
    <label class="form-label" for="form3Examplea3" style="color: black;">Rooms (min)</label>
      <%= onboarding_form.text_field "filter[room]", class: "form-control form-control-lg" %>
    </div>

    <div class="form-outline form-white not-top-label">
      <label class="form-label" for="form3Examplea4" style="color: black;">Rent (max)</label>
      <%= onboarding_form.text_field "filter[rent]", class: "form-control form-control-lg" %>
    </div>

    <div class="form-check d-flex justify-content-start mb-4 pb-3 not-top-label" >
      <input class="form-check-input me-3" type="checkbox" value="" id="form2Example3c" />
      <label class="form-check-label text-white" for="form2Example3" style="color: black;">
        I do accept the <a href="#!"><u>Terms and Conditions</u></a> of your
        site.
      </label>
    </div>
  </div>

  <button type="submit" class="btn btn-light btn-lg register-button" data-mdb-ripple-color="dark"> Register </button>
</div>

app/views/onboarding/new.html.erb
<%= render 'shared/navbar_onboarding' %>

<%= form_with url: onboarding_path  do |onboarding_form| %>
 <div class="forms">
  <%= render "onboarding/apartment_form", onboarding_form: onboarding_form %>
  <%= render "onboarding/filter_form", onboarding_form: onboarding_form %>
 </div>
<% end %>

<footer class="bg-light text-center text-white">
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

    </section>

  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">TauschMe</a>
  </div>
</footer>