config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :apartments do
    :filters
  end

  get "/onboarding", to: "onboarding#new"
  post "/onboarding", to: "onboarding#create"

  devise_for :users, controllers: { registrations: "registrations" }

  resources :statuses, only:[:new, :create]

  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :user
  has_many_attached :photos, dependent: :destroy
  validates :title, presence: true
  validates :rent, numericality: { only_integer: true }, presence: true
  validates :room, numericality: { only_integer: true }, presence: true
  validates :area, presence: true

end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  def index
    if current_user.present?
      @filter = current_user.filter
      return redirect_to(onboarding_path, notice: "You need to add your apartment first") if @filter.nil?
      # filter out current user
      @apartments = Apartment.where.not(user_id: current_user.id)
      @apartments = @apartments.where(area: @filter.area)
      @apartments = @apartments.where(room: @filter.room..20)
      @apartments = @apartments.where(rent: 0..@filter.rent)
      @apartments = @apartments.reject do |apartment|
        current_user.active_statuses.pluck(:user1_id, :user2_id).flatten.include?(apartment.user_id)
      end
    else
      @apartments = Apartment.all
    end
  end

  def show
    @apartment = Apartment.find(params[:id])
  end

  def edit
  end

  def new
    @apartment = Apartment.new
  end

  def update
    if @apartment.update(apartment_params)
      redirect_to @apartment, notice: 'Your apartment was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @apartment = Apartment.new(apartment_params)
  end

  def destroy
    @apartment = Apartment.find(params[:id])
    @apartment.destroy
    redirect_to apartments_path
  end

  private

  def apartment_params
    params.require(:apartment).permit(:title, :description, :room, :area, :rent, photos: [])
  end

end

app/views/apartments/index.html.erb
<%= render 'shared/navbar_index' %>



<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
  <div class="carousel-inner index-card">
  <% if @apartments.empty? %>
    <h3 class="text-center">You have seen all available apartments. Wait a few hours and try again...</h3>
  <% end %>
    <% @apartments.each_with_index do |apartment, index| %>
     <div class="carousel-item <%= "active" if apartment == @apartments.first %>">
        <%= link_to apartment_path(apartment) do %>
        <div class="carousel-card">
          <div class="d-flex" style="height: 100%;" >
          <div class="apartment-info">
            <div>

              <p class="card-title"><%= apartment.title %></p>
              <%# <p><%= apartment.description %></p>
            </div>
            <div>
              <p><i class="fa-solid fa-location-dot icon-ad"></i><%= apartment.area %></p>
              <p><i class="fa-solid fa-house icon-ad-house"></i></i>Rooms: <%= apartment.room %></p>
              <p><i class="fa-solid fa-euro-sign icon-ad"></i><%= apartment.rent %>/ month</p>
            </div>
          </div>
          <div class="apartment-picture">


              <% if apartment.photos.attached? %>
              <%= cl_image_tag apartment.photos.last.key %>
              <% end %>


          </div>
          </div>
        </div>

        <% end %>
        <div class="likebutton">
          <button id="dislike" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <%= button_to statuses_path(user: apartment.user, status: "disliked"), method: :post, id: "dislike" do %>
          <i class="fa-solid fa-circle-xmark fa-4x buttoncolor"></i>
          <% end %>
          <span class="visually-hidden">Previous</span>
        </button>
        <button id="like" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <%= button_to statuses_path(user: apartment.user, status: "liked"), method: :post, id: "like" do %>
          <i class="fa-solid fa-circle-check fa-4x buttoncolor"></i>
          <% end %>
          <span class="visually-hidden">Next</span>
        </button>
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/apartments/show.html.erb
<%#= render 'shared/navbar_show' %>
<div class="carousel_container">
  <%= render 'shared/image_carousel' %>
</div>